
server:
  port: 8091

spring:
  application:
    name: report-generation-app
  
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: report-generation-client
            client-secret: L8n9DHRAf6A0p8rBM62jaqdtMjAGkPoJ
            scope: openid,profile,email,roles
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            redirect-uri: "{baseUrl}/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/multi-app-realm
            user-name-attribute: preferred_username
      
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/multi-app-realm
          jwk-set-uri: http://localhost:8081/realms/multi-app-realm/protocol/openid-connect/certs

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

keycloak:
  auth-server-url: http://localhost:8081
  realm: multi-app-realm
  resource: report-generation-client

app:
  frontend-url: http://localhost:3001
  landing-page-url: http://localhost:3000
  reports:
    storage-path: ./reports
  
logging:
  level:
    root: INFO
    com.company.landing: DEBUG
    org.keycloak: DEBUG    
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE